### PR TITLE
Added SEPT21C

### PR DESCRIPTION
**Pull request by nitish-awasthi**

### CODE REVIEW

**Comment by Anishukla** [comment]
Approved and merged

**Comment by Anishukla** [comment]
Will be better if you can provide the link for verification if they are AC. Do it in the code itself as a comment.

**Comment by nitish-awasthi** [comment]
Sure

**Comment by nitish-awasthi** [comment]
https://www.codechef.com/viewsolution/50689052
https://www.codechef.com/viewsolution/50689376

**Pull request merged**
